version: "3"
services:
  app:
    image: registry.cn-shenzhen.aliyuncs.com/qskane/imgtrip-ts:staging-latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    env_file:
      - ts_app_staging.env
    command: bash -c "echo \"TZ='Asia/Shanghai'; export TZ\" >> ~/.profile && source ~/.profile && cd /app && npm run start"
    networks:
      - webnet
networks:
  webnet:
